### ISSUE TITLE
Is it possible to draw lines and dots programatically?

### ISSUE THREAD

**Issue by alexcd2000** [Mathieu2301/TradingView-API#104]
Hi Mathieu!! 

your library looks great man! Ive browsed through the examples but the only feature Im looking for is to draw lines and dots upon a chart like this:
![tv](https://user-images.githubusercontent.com/68623827/171755515-ad0420ad-152e-4fac-954b-7c04abf152f4.jpg)

Is it possible to do it with your libreary? if so is there a specific example for it Ive overlooked... or can you create one?? 
It would really really help me out to solve my project, I would love to send some btc on appreciation if it did.

Sorry for the disturbance!! lets keep in touch!
Alex

**Comment by Mathieu2301** [comment]
Hello, it is not currently possible but it can be easily implemented, but unfortunately I don't have time to do it now. Sorry...

**Comment by minhlucvan** [comment]
so nice package actually

**Comment by mmaestrini** [comment]
Anyone had this need again? it would be really nice to have that but i have no clue how to go about it :/
