### ISSUE TITLE
Error: Please confirm that you are not a robot by clicking the captcha box.

### ISSUE THREAD

**Issue by Joeo1** [Mathieu2301/TradingView-API#126]
What do we do when this error message is shown when trying to loginUser()? 
Due to a testing error I fired too many requests in a short amount of time. Now it keeps asking.

```
Error: Please confirm that you are not a robot by clicking the captcha box.
```

Replicate by running this code (maybe a couple of times)

```
for (let i = 0; i < 100; i++) {

        TradingView.loginUser('user', 'pw', false).then((user) => {

        });
}
```

**Comment by Mathieu2301** [comment]
We can't do anything...
This function has to be only used to generate one sessionid. Then you should connect with the same sessionid which is valid during a very long period.

**Comment by Joeo1** [comment]
Good to know. 

So, any ideas on how to connect again? I tried logging out and logging in in my browser, and it was indeed asking to do the captcha. But when firing up my node.js program again it keeps asking to click the captcha box.

**Comment by Mathieu2301** [comment]
Nope, use your `sessionid` cookie

**Comment by Joeo1** [comment]
Thanks I did not think about that! Eventually the program will run on a different server anyway, so for now this will work.
Will be exploring your work more in the upcoming days, thanks for sharing it with us!
