### ISSUE TITLE
setMarket{to: } not working

### ISSUE THREAD

**Issue by Joeo1** [Mathieu2301/TradingView-API#129]
Hi Mathieu,

It seems that "to" in the setMarket function is not working.

```
chart.setMarket('BYBIT:BTCUSD', {
					  
        timeframe: '1D',
        range: 300,
        to: Date.now(),
});

// load volume profile indicator and set options
let volume_profile = new TradingView.BuiltInIndicator('VbPSessions@tv-volumebyprice-53');
let volume_profile_study = new chart.Study(volume_profile);

// get study values
volume_profile_study.onUpdate(() => {

        volume_profile_study.graphic.horizLines.forEach((h) => {
               
              console.log(h);
        });
});
is returning the exact same results as

chart.setMarket('BYBIT:BTCUSD', {
					  
        timeframe: '1D',
        range: 300,
        to: 1600000000000,
});

// load volume profile indicator and set options
let volume_profile = new TradingView.BuiltInIndicator('VbPSessions@tv-volumebyprice-53');
let volume_profile_study = new chart.Study(volume_profile);

// get study values
volume_profile_study.onUpdate(() => {

        volume_profile_study.graphic.horizLines.forEach((h) => {
               
              console.log(h);
        });
});
```

How do I get data before 1600000000000 (Sun Sep 13 2020 12:26:40 GMT+0000)? (as an example)

Appreciate your reply! Joe

**Comment by Joeo1** [comment]
It seems that graphicParse() is limiting the amount of rawGraphic results returned after calling graphic study.graphic.
It is because the amount of indexes is lower when going into graphicParse(rawGraphic = {}, indexes = [])

Is there a setting I should change to get the indexes right?

**Comment by Joeo1** [comment]
Never mind, I am obviously not getting how your library works. Will see if I can dive into your code more to try and understand it. Documentation would be very valuable for this project, maybe if I understand it better I can make a documentation draft.

**Comment by 0x090909** [comment]
hwy man did you figure out a solution for this? Im facing a similar problem
