### ISSUE TITLE
I want to change graphic bar

### ISSUE THREAD

**Issue by YunusAkbalik** [Mathieu2301/TradingView-API#14]
Hello Mathieu,
I want to change this 
![Adsız](https://user-images.githubusercontent.com/58446763/140319239-12faa9da-7fc8-4dd8-9034-d450b7576755.png)
on script.
Because of your code using default candle bar but my indicators giving true info with 'Heikin Ashi'. Can u help me :)

**Comment by Mathieu2301** [comment]
Hello, thank you for the suggestion.
It won't be possible to do it with v2 but I will make it possible with v3 tomorrow !

**Comment by YunusAkbalik** [comment]
Thx ^^

**Comment by Mathieu2301** [comment]
Hello !

You can now set `type` property when calling `chart.setMarket('...', { ... })` method :
```javascript
const chart = new client.Session.Chart();
chart.setMarket('BINANCE:SHIBEUR', {
  type: 'HeikinAshi',
});
chart.setSeries('15');
```

It works with `HeikinAshi`, `Renko`, `LineBreak`, `Kagi`, `PointAndFigure` and `Range`.

If you want to try with other types, you have to set some required options.
For example with `Renko` :
```javascript
const chart = new client.Session.Chart();
chart.setMarket('BINANCE:SHIBEUR', {
  type: 'Renko',
  inputs: {
    atrLength: 15,
    source: 'close',
    style: 'ATR',
    boxSize: 3,
  },
});
chart.setSeries('D');
```

With these types, you can't use it in intraday without having a paid TradingView account.
So doing `chart.setSeries('60');` without being logged will return an error.
