### ISSUE TITLE
How to load my session with private indicators?

### ISSUE THREAD

**Issue by marcelbonnet** [Mathieu2301/TradingView-API#15]
Hi, I'd appreciate your help in this matter. 

I tried this ... I'm reading the sources to figure it out with no luck .

Thanks in advance.

```
const marketAPI = require('@mathieuc/tradingview');
const market = marketAPI(false);



market.on('logged', () => {
  market.initChart({
    session: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    symbol: 'BTCPERP',
    period: '5',
    range: 100,
    indicators: [
      {
        name: 'My Indicator',
        id: market.searchIndicator('My Indicator').then(r => {id = r[0].id; return id}),
        version: '51.0',
        // settings: {
        //   commission_type: 'percent',
        //   commission_value: 0,
        //   initial_capital: 25000,
        //   default_qty_value: 20,
        //   default_qty_type: 'percent_of_equity',
        //   currency: 'EUR',
        //   pyramiding: 10,
        // },
      },
    ],
  }, (_, strategy) => {
    console.log(strategy);
  });

  
});
```

**Comment by marcelbonnet** [comment]
Well, I played around, but I still not understanding:

- how to load my session (I found the attribute _sessionId_, but I have no idea how to set it)
- I ran an indicator example from Issue #9 (STD;Supertrend%Strategy) with success. But, after changing that indicator to _STD;Volume_ , I got no results from terminal. Is it mandatory to configure the _settings_ ? How to know the parameter names?

In fact, I would like to load my private indicators and also receive volume data.

**Comment by Mathieu2301** [comment]
Hi !
First, `market.searchIndicator('My Indicator').then(r => {id = r[0].id; return id})` can't work and you should replace it by an `await` call (or directly by the indicator ID).

Then, `STD;Supertrend%Strategy` is a strategy and `STD;Volume` is just a study !

Your code works with **strategies** but if you want to get **study** data, your code should be something like that :
```javascript
market.initChart({
  symbol: 'BTCPERP',
  period: '5',
  range: 100,
  indicators: [
    {
      name: 'VOL',
      id: 'STD;Volume',
      version: 'last',
    },
  ],
}, (data) => {
  if (data[0].VOL) console.log('Last plot', data[0].VOL);
});
```

With v2 it's complicated to define the indicator options.
Usually the properties are in the order they are displayed on tradingview.
Like I said in #9, you can use the v3 to help you with the settings.

**Comment by marcelbonnet** [comment]
Thanks @Mathieu2301 !

I made some progress after that.

About loading a TradingView session ...  I tried adding a _sessionId_ attribute to _initChart()_  . Is this the right way?  The value, I suppose must be the same from _sessionid_ in my browser.
 
```
market.on('logged', () => {
  market.initChart({
    sessionId: 'xxxxxxxx',
    symbol: 'BTCPERP',
    period: '5',
    range: 100,
    indicators: [
...
```

**Comment by marcelbonnet** [comment]
Finally! I loaded my session and a private strategy.

I was not capable to _market.searchIndicator_ and find my private one.  I think the function is searching for public ones (correct me if I'm wrong). Anyway, I found its ID   :

- opening my layout in Firefox
- open developer tools
- click the tradingview button "fx"
- use the dev tools to select the element that has the indicator you want on the pop up that shows/filters the functions/strategies
- there is a DIV with a data-id attribute and the id is something like USER;xxxxxxxxxxxx

The code:

```
const my_sessionid = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
const my_layout = 'zzzzz';


market.on('logged', () => {

  market.initChart({
    session: my_sessionid,
    symbol: 'BTCPERP',
    period: '5',
    range: 100,
    indicators: [
      {
        name: 'My Strategy',
        id: 'USER;wwwwwwwwwwwwwwwwwwwwwww',
        version: '51.0',
        // settings: {
        //  TODO
        // },
      },
    ],
  }, (_, strategy) => {
    console.log(strategy);
  });
});
```

**Comment by Mathieu2301** [comment]
Yes you did it the right way. Maybe I will add a way to get private indicator list.

**Comment by Mathieu2301** [comment]
Update :

I made a `getPrivateIndicators` function :
```javascript
const indicList = await TradingView.getPrivateIndicators('YOUR_SESSION_ID_COOKIE');
console.log('Private indicators:', indicList);
```

Then we can imagine a chart with all user's private indicators :
```javascript
const client = new TradingView.Client({
  token: 'YOUR_SESSION_ID_COOKIE', // Only needed if at least one indicator is PRIVATE (if you have paid TradingView account)
});

const chart = new client.Session.Chart();
chart.setMarket('BINANCE:SHIBEUR');
chart.setSeries('D');

TradingView.getPrivateIndicators('YOUR_SESSION_ID_COOKIE').then((indicList) => {
  indicList.forEach(async (indic) => {
    const privateIndic = await indic.get();
    console.log('Loading indicator', indic.name, '...');

    const indicator = new chart.Study(privateIndic);

    indicator.onReady(() => {
      console.log('Indicator', indic.name, 'loaded !');
    });

    indicator.onUpdate(() => {
      console.log('Plot values', indicator.periods);
      console.log('Strategy report', indicator.strategyReport);
    });
  });
});
```
