### ISSUE TITLE
Pro in-built indicators (Volume profile, Visible Range, ...)

### ISSUE THREAD

**Issue by duclh-2011** [Mathieu2301/TradingView-API#18]
Hi Mathieu ! 
I'm very excited about your code.
Currently I am having problems with pro indicators such as  volume profile visible range .

![image](https://user-images.githubusercontent.com/54925990/141489957-682c90d6-6435-4998-a0e2-2a2c1628c068.png)

i try by my code , but it's is impossible

<img width="1075" alt="Screen Shot 2021-11-13 at 0 19 29" src="https://user-images.githubusercontent.com/54925990/141490390-fb37d064-bd5b-41f7-8c5a-50fd812b5297.png">
  
Can you help me ?

**Comment by Mathieu2301** [comment]
Indeed we cannot find this indicator with the `searchIndicator` function.
But I dont have a premium TradingView account so I can't debut that.

Are you sure of `VbPVisible@tv-volumebyprice` ? Did you found it by looking at websockets ?
If yes, please send the raw request value ? Something like that :
```json
{
  "m": "create_study",
  "p": [
    "cs_xJ34Id8qyJ35",
    "st3",
    "st1",
    "sds_1",
    "Earnings@tv-basicstudies-138",
    {}
  ]
}
```

**Comment by duclh-2011** [comment]
@Mathieu2301 
Hi Mathieu2301, i see your answer in [here](https://github.com/Mathieu2301/TradingView-API/issues/15#issuecomment-962163116 ), then i try with your example
this is my video, can you tell me why i can run it ? 


https://user-images.githubusercontent.com/54925990/141647110-48231107-f530-4ae0-bd74-1a43a744dcc6.mp4


in my case it didn't run any results, and so on.
My indicator is 
1- MCDX SmartMoney , ID : PUB;3lEKXjKWycY5fFZRYYujEy8fxzRRUyF3 
2- Baz: Mcdx Heatmap , ID : PUB;IpKGQeW0SKt4ICjBAG6XUjVh1DHscFvS 
2 indicators above, need an account to run (no need for a pro account, just a normal account)
can you check it for me ?

**Comment by Mathieu2301** [comment]
> 1- MCDX SmartMoney , ID : PUB;3lEKXjKWycY5fFZRYYujEy8fxzRRUyF3
2- Baz: Mcdx Heatmap , ID : PUB;IpKGQeW0SKt4ICjBAG6XUjVh1DHscFvS
2 indicators above, need an account to run (no need for a pro account, just a free account)
can you check it for me ?

No. These indicators are PUBLIC.

I have deleted your last message for security reasons. Please dont share your sessionid cookie here, especially if you have a premium tradingview account.

The `getPrivateIndicators` function is used to get user's indicators (useful to get the ID of a PRIVATE indicator without using DevTools).

**Comment by Mathieu2301** [comment]
And `Baz: Mcdx Heatmap` works better with the `v3` of my library. Then your code should looks like :

```javascript
(async () => {
  const client = new TradingView.Client();

  const chart = new client.Session.Chart();
  chart.setMarket('BINANCE:DOTUSDT');

  const indicator = await TradingView.getIndicator('PUB;IpKGQeW0SKt4ICjBAG6XUjVh1DHscFvS');

  const HeatMap = new chart.Study(indicator);

  HeatMap.onUpdate(() => {
    console.log('Plot values', HeatMap.periods);
  });
})();
```

**Comment by duclh-2011** [comment]
Thank you for your help. I am very happy for that. I'm having trouble getting out of the loop. This is my code.

 i want to remove it after i got the data at first time but it doesn't break out of the loop and waiting here

<img width="804" alt="Screen Shot 2021-11-15 at 18 02 07" src="https://user-images.githubusercontent.com/54925990/141752671-21507880-f67e-458e-93d2-2ca5f20ccf48.png">

How can I get data from another indicator when it doesn't breakout loop ?

**Comment by Mathieu2301** [comment]
I dont understand what you are trying to do. If you want to end the process you have to do a `client.end();`

```javascript
const TradingView = require('../main');

(async () => {
  const client = new TradingView.Client();

  const chart = new client.Session.Chart();
  chart.setMarket('BINANCE:DOTUSDT');

  const indicator = await TradingView.getIndicator('PUB;3lEKXjKWycY5fFZRYYujEy8fxzRRUyF3');

  const HeatMap = new chart.Study(indicator);

  HeatMap.onUpdate(() => {
    console.log('Plot values', HeatMap.periods);
    console.log('Done !');
    client.end();
  });
})();
```

**Comment by duclh-2011** [comment]
@Mathieu2301 

I want to get data from many different indicators, so if I use `client.end();` it will close the session.

```javascript
const TradingView = require('../main');

(async () => {
  const client = new TradingView.Client();

  const chart = new client.Session.Chart();
  chart.setMarket('BINANCE:DOTUSDT');

  const indicator = await TradingView.getIndicator('PUB;3lEKXjKWycY5fFZRYYujEy8fxzRRUyF3');
  const indicator2 = await TradingView.getIndicator('PUB;5nawr3gCESvSHQfOhrLPqQqT4zM23w3X');
  const indicator3 = await TradingView.getIndicator('PUB;vrOJcNRPULteowIsuP6iHn3GIxBJdXwT');


  const HeatMap = new chart.Study(indicator);
  const CIPHER_A = new chart.Study(indicator3);
  const CCMA = new chart.Study(indicator3);

  var dataIndicator1;
  var dataIndicator2;
  var dataIndicator3;

  HeatMap.onUpdate(() => {
    console.log('Plot values', HeatMap.periods);
    dataIndicator1 = HeatMap.periods;
    console.log('Done !');
    // if use client.end(); here, it will close all 
    client.end();
  });

  CIPHER_A.onUpdate(() => {
    console.log('Plot values', CIPHER_A.periods);
    dataIndicator2 = CIPHER_A.periods;
    // if use client.end(); here, it will close all 
    client.end();
  }
  CCMA.onUpdate(() => {
    console.log('Plot values', CCMA.periods);
    dataIndicator3 = CCMA.periods;
    // if use client.end(); here, it will close all 
    client.end();
  }

})();

```

Can you help me ?

**Comment by duclh-2011** [comment]
@Mathieu2301 Nice! 
i just learned javascript 2 months. Thank you for the help! Thank you very much !
