### ISSUE TITLE
Volume in-built indicators (Volume profile, Visible Range, ...)

### ISSUE THREAD

**Issue by duclh-2011** [Mathieu2301/TradingView-API#19]
Hi @Mathieu2301 
I try to get ID Indicator Built-ins (example Visible Range) in Volume Profile (look my image) but i can't do that 

I tried using function `searchIndicator` but it didn't work. (didn't get the result I wanted)

can you help me ?

![image](https://user-images.githubusercontent.com/54925990/141966473-ce3f4fae-e042-4fb4-9fe7-d3bc1ce83487.png)

**Comment by Mathieu2301** [comment]
Indeed we cannot find this indicator with the `searchIndicator` function.
But I dont have a premium TradingView account so I can't debut that.

Please go in Network tab, select the Websocket and send here the raw `create_study` request full value.

![image](https://user-images.githubusercontent.com/21021423/141971059-3e4cca99-98f0-4e43-a72b-4b466c82f5c4.png)

**Comment by Mathieu2301** [comment]
Indeed we cannot find this indicator with the `searchIndicator` function.
But I dont have a premium TradingView account so I can't debut that.

Please go in Network tab, select the Websocket and send here the raw `create_study` request full value.

![image](https://user-images.githubusercontent.com/21021423/141971059-3e4cca99-98f0-4e43-a72b-4b466c82f5c4.png)
![image](https://user-images.githubusercontent.com/21021423/141971374-2373e2c2-f15e-4db2-b8e9-0cd7cf975a80.png)

**Comment by duclh-2011** [comment]
@Mathieu2301 
here is ws request, please check for me ! 
```json
{"m":"create_study","p":["cs_eYKheDFksjv9","st5","st1","sds_1","VbPVisible@tv-volumebyprice-53",{"rowsLayout":"Number Of Rows","rows":24,"volume":"Up/Down","first_visible_bar_time":1629936000000,"last_visible_bar_time":1637020800000,"vaVolume":70,"subscribeRealtime":true}]}
```

**Comment by xiaopihaiK** [comment]
I want to get the value of the indicator on the chart, how do I do it? Thanks! Or download the csv file of the current chart

**Comment by xiaopihaiK** [comment]
do you have python code , I am not too familiar with js，thank you!

**Comment by Mathieu2301** [comment]
> do you have python code , I am not too familiar with js，thank you!

This project is a Javscript library for TradingView.

**Comment by Mathieu2301** [comment]
> @Mathieu2301 here is ws request, please check for me !
> 
> ```json
> {"m":"create_study","p":["cs_eYKheDFksjv9","st5","st1","sds_1","VbPVisible@tv-volumebyprice-53",{"rowsLayout":"Number Of Rows","rows":24,"volume":"Up/Down","first_visible_bar_time":1629936000000,"last_visible_bar_time":1637020800000,"vaVolume":70,"subscribeRealtime":true}]}
> ```

Thank you, I will see what I can do.

**Comment by duclh-2011** [comment]
> > @Mathieu2301 here is ws request, please check for me !
> > ```json
> > {"m":"create_study","p":["cs_eYKheDFksjv9","st5","st1","sds_1","VbPVisible@tv-volumebyprice-53",{"rowsLayout":"Number Of Rows","rows":24,"volume":"Up/Down","first_visible_bar_time":1629936000000,"last_visible_bar_time":1637020800000,"vaVolume":70,"subscribeRealtime":true}]}
> > ```
> 
> Thank you, I will see what I can do.

can you share us how to find id from ws request  ?

**Comment by Mathieu2301** [comment]
This special indicator is not a script so it doesn't have a Pine ID.

**Comment by duclh-2011** [comment]
> This special indicator is not a script so it doesn't have a Pine ID.

so, how can i get data from this indicator ? Do you have any way ?

**Comment by xiaopihaiK** [comment]
For example, if I want to get this content, what content should I send to the server?
![image](https://user-images.githubusercontent.com/52098233/142013097-7338cdbf-e4ec-4e6c-9c5c-62155bdd86ec.png)

**Comment by Mathieu2301** [comment]
> > This special indicator is not a script so it doesn't have a Pine ID.
> 
> so, how can i get data from this indicator ? Do you have any way ?

I will try to implement it in V3 but currently I can't debug it because I dont have a Premium TradingView account.

**Comment by xiaopihaiK** [comment]
I can help you solve the account problem

**Comment by duclh-2011** [comment]
> > > This special indicator is not a script so it doesn't have a Pine ID.
> > 
> > 
> > so, how can i get data from this indicator ? Do you have any way ?
> 
> I will try to implement it in V3 but currently I can't debug it because I dont have a Premium TradingView account.

Can I help you with anything?

**Comment by Mathieu2301** [comment]
No, thank you but I will use TW 30 days trial.

**Comment by xiaopihaiK** [comment]
For example, if I want to get this content, what content should I send to the server?
[https://user-images.githubusercontent.com/52098233/142013097-7338cdbf-e4ec-4e6c-9c5c-62155bdd86ec.png](url)
thank you!

**Comment by duclh-2011** [comment]
> No, thank you but I will use TW 30 days trial.

thank you. 
so I'll let this issue open until you have new update.

**Comment by Mathieu2301** [comment]
> > > > This special indicator is not a script so it doesn't have a Pine ID.
> > > 
> > > 
> > > so, how can i get data from this indicator ? Do you have any way ?
> > 
> > 
> > I will try to implement it in V3 but currently I can't debug it because I dont have a Premium TradingView account.
> 
> Can I help you with anything?

YES :)
You can send me the WS request for the others Volume-based indicators !
![image](https://user-images.githubusercontent.com/21021423/142015440-651ea8af-ec92-40ce-b94f-b73fbd0a0990.png)

**Comment by duclh-2011** [comment]
> YES :) You can send me the WS request for the others Volume-based indicators ! ![image](https://user-images.githubusercontent.com/21021423/142015440-651ea8af-ec92-40ce-b94f-b73fbd0a0990.png)

which indicator do you want ? all of 4 indicator or special one ?

**Comment by duclh-2011** [comment]
new request: 

```json
{"m":"create_study","p":["cs_xhcBBHg5iEWR","st5","st1","sds_1","VbPVisible@tv-volumebyprice-53",{"rowsLayout":"Number Of Rows","rows":24,"volume":"Up/Down","first_visible_bar_time":1634112000000,"last_visible_bar_time":1637064000000,"vaVolume":70,"subscribeRealtime":true}]}
```

**Comment by duclh-2011** [comment]
new request : session volume 

```json
{"m":"create_study","p":["cs_xhcBBHg5iEWR","st9","st1","sds_1","VbPSessions@tv-volumebyprice-53",{"rowsLayout":"Number Of Rows","rows":24,"volume":"Up/Down","vaVolume":70,"extendPocRight":false}]}
```

**Comment by duclh-2011** [comment]
tell me if you need anything else @Mathieu2301

**Comment by duclh-2011** [comment]
@Mathieu2301  do you have anything news?

**Comment by Mathieu2301** [comment]
I implemented the `BuiltInIndicator` object. You can use it now like in [this example](https://github.com/Mathieu2301/TradingView-API/blob/v3.0-remake/examples/BuiltInIndicator.js).
The data provided by Volume Indicators is `graphic` data and have to be parsed !
The `graphicParser` should do it in the future, I will work on it.

**Comment by Mathieu2301** [comment]
@duclh-2011 
Hello ! I've just implemented the support of all the volume-based indicators ! You can now get bars values :
```javascript
const client = new TradingView.Client({
  token: 'YOUR_TOKEN',
});

const chart = new client.Session.Chart();
chart.setMarket('BINANCE:BTCEUR', {
  timeframe: '60',
  range: 1,
});

const volumeProfile = new TradingView.BuiltInIndicator('VbPSessions@tv-volumebyprice-53');

/* Required for other volume-based built-in indicators */
// volumeProfile.setOption('first_bar_time', 1639080000000);
// volumeProfile.setOption('last_bar_time', 1639328400000);
// volumeProfile.setOption('first_visible_bar_time', 1639080000000);
// volumeProfile.setOption('last_visible_bar_time', 1639328400000);

const VOL = new chart.Study(volumeProfile);
VOL.onUpdate(() => {
  VOL.graphic.hists
    .filter((h) => h.lastBarTime === 0) // We only keep recent volume infos
    .sort((a, b) => b.priceHigh - a.priceHigh)
    .forEach((h) => {
      console.log(
        `~ ${Math.round((h.priceHigh + h.priceLow) / 2)} € :`,
        `${'_'.repeat(h.rate[0] / 3)}${'_'.repeat(h.rate[1] / 3)}`,
      );
    });

  client.end();
});
```

<img width="512" alt="image" src="https://user-images.githubusercontent.com/21021423/145688154-7f940483-8a38-4327-b864-4ddef1a76080.png">
<img width="523" alt="image" src="https://user-images.githubusercontent.com/21021423/145687256-857c0227-a9a0-4acd-bdd3-d6eaee4e4937.png">

**Comment by dallastownsend** [comment]
why was this closed it was just getting good!

**Comment by Mathieu2301** [comment]
> why was this closed it was just getting good!

Because the feature has been implemented
