### ISSUE TITLE
how to get specific stock prices

### ISSUE THREAD

**Issue by sekomer** [Mathieu2301/TradingView-API#206]
I want to get specific stock prices from specific market, for example THYAO from BIST(Turkish) market. How can I achieve this with this library?

**Comment by Judith-Alvarez** [comment]
@sekomer Hey, did you got it wotking? I also need to fetch the candlestick data to json or something

**Comment by sekomer** [comment]
nope I ditched the project and started another one 😆

hit me up if you find a way

**Comment by Judith-Alvarez** [comment]
@sekomer You need Session.Chart() example of its' usage is in /TradingView-API/examples/SimpleChart.js
