### ISSUE TITLE
Snapshot and share Tradingview image ?

### ISSUE THREAD

**Issue by duclh-2011** [Mathieu2301/TradingView-API#21]
Hi @Mathieu2301 !
Do you have any ideas on how to create Snapshot and share Tradingview image functionality?

I found this document, but was wondering if it is possible to do it with your code?

https://www.tradingview.com/support/solutions/43000482537-how-do-i-take-a-snapshot-and-share-it-afterwards/

**Comment by Mathieu2301** [comment]
No it's not possible because my library isn't emulating the UI.

**Comment by duclh-2011** [comment]
Thank you ~~
