### ISSUE TITLE
Series error: seconds_not_entitled

### ISSUE THREAD

**Issue by VRspace4** [Mathieu2301/TradingView-API#22]
Hi @Mathieu2301. Really appreciate you sharing this awesome TradingView project!

I currently have a Premium subscription with TradingView, which includes second-based charts. However, when I attempt to create a second-based, '1S', chart session even with a valid sessionid/token, it prompts this error: "Series error: seconds_not_entitled". The following is the code snippet:

```
const TradingView = require('../main');

const privateSessionId = process.env.TRADINGVIEW_SESSIONID;

const client = new TradingView.Client({
  token: privateSessionId,
});

const chart = new client.Session.Chart();
chart.setMarket('BINANCE:BTCEUR', {
  timeframe: '1S',
});

```

I've confirmed any other timeframe works, e.g. 1, 5, 10, W, etc.

Also, I have tried running the example, AllPrivateIndicators.js, with the same private Session ID and have confirmed that it does work.

**Comment by Mathieu2301** [comment]
Hello !
Fixed it in last commit. Please tell me if all is ok.

**Comment by VRspace4** [comment]
That was fast! Works perfectly now. Thanks!
