### ISSUE TITLE
getIndicator no longer works for Indicators with Id's starting with 'USER;' and only works for Indicators with Id's starting with 'PUB;'

### ISSUE THREAD

**Issue by TaylorArmstrong** [Mathieu2301/TradingView-API#249]
**Describe the bug**
getIndicator fails with the following error thrown from misRequests.js line 257 : 'The user requesting information on the script is not allowed to do so'
getIndicator succeeds with ID starting with 'PUB;' , but not 'USER;'

**To Reproduce**
Code to reproduce the behavior.

        const client = new TradingView.Client({token: process.env.TRADINGVIEW_SESSION_ID, signature: process.env.TRADINGVIEW_SESSION_ID_SIGN});
        const chart = new client.Session.Chart();

        chart.setMarket(symbol, {
            timeframe: timeframe.toString(),
            type: 'HeikinAshi',
            to: _to,
            range: number_of_candles,
            session: 'extended'
        });
        
        TradingView.getIndicator(indicator).then(indic => {

            const study = new chart.Study(indic);

        })

**Expected behavior**

08/05 - This same code was working and returning data for all indicators. Could this be an issue with the account or a permissions issue? Nothing has changed that we are aware of. 

**Screenshots**

**Environment:**
 - OS: mac Sonoma 14.5
 - Node version: v20.15.0

**Additional context**

**Comment by ZhangJiankun-1997** [comment]
it lost cookies, pass it in [`src/miscRequest.js`](https://github.com/Mathieu2301/TradingView-API/blob/d059938dacc5800afec5bac78a181015aae23359/src/miscRequests.js#L253) like this:

```diff
  const { data } = await axios.get(
    `https://pine-facade.tradingview.com/pine-facade/translate/${indicID}/${version}`,
-    { validateStatus },
+   { validateStatus,
+     headers: {
+         cookie: `sessionid=${session}${signature ? `;sessionid_sign=${signature};` : ''}`,
+      }
+   },
  );
```

**Comment by aiyunstunna** [comment]
This bug is back.  It was fixed as of yesterday and now the same issue occurs.

**Comment by aiyunstunna** [comment]
Nvm it only affects the Replay mode and I fixed it.
