### ISSUE TITLE
Wrong or expired sessionid/signature error even for valid tokens during client initialization

### ISSUE THREAD

**Issue by narayanan-gokul** [Mathieu2301/TradingView-API#259]
**Describe the bug**
While instantiating a client using a session id, a `Wrong or expired sessionid/signature` is thrown even for correct credentials.

**To Reproduce**
Create a client using valid session id and signature but for an account based in a country with the location prefix (ex: France, and in my case: India)

**Expected behavior**
There shouldn't be any errors whatsoever.

**Environment:**
 - OS: archlinux
 - Node version: 18.20.4

**Comment by naveenaryag** [comment]
Same issue can't get pass session id and signature
