### ISSUE TITLE
How to get all symbols from an exchange

### ISSUE THREAD

**Issue by duclh-2011** [Mathieu2301/TradingView-API#26]
hi @Mathieu2301  !
How to get all symbols from a market ? example get all symbols from Binance or Houbi ? i see `searchMarket` , but it only looks for a specified symbol, not all symbols in the market.

**Comment by Mathieu2301** [comment]
Hello, you have to put a ':' after the exchange name :
```javascript
TradingView.searchMarket('BINANCE:')
```
not
```javascript
TradingView.searchMarket('BINANCE')
```

**Comment by duclh-2011** [comment]
Hi @Mathieu2301 

this is my code : 

```javascript
const searchSymbol = await TradingView.searchMarket("BINANCE:", "crypto");
  console.log(searchSymbol.length);
}
```

and the result is : **50**

I'm sure there can't be only 50 Symbols on binance, right?
<img width="838" alt="Screen Shot 2021-11-27 at 21 08 21" src="https://user-images.githubusercontent.com/54925990/143680686-89a529cf-65ad-4ac8-ac3a-4699c69ac81e.png">

I have looked at your source code, but don't see pagination. Am I missing out on something?

**Comment by Mathieu2301** [comment]
Okay, TradingView sends a maximum of 50 items when you search a Market.
So it's impossible (unless you find a place on the website where we can get them all or use a pagination).

**Comment by duclh-2011** [comment]
@Mathieu2301 ok, thankyou ! i understand !

**Comment by MrKitai** [comment]
I think here you may find the complete list you're searching for.

https://github.com/oktrader/tradingview-watchlists/
