### ISSUE TITLE
Get error when run MultipleSyncFetch.js: "The maximum number of studies per chart has been reached for current subscription"

### ISSUE THREAD

**Issue by huynhduc96** [Mathieu2301/TradingView-API#269]
**Describe the bug**

Basically I'm re-running the functions in `MultipleSyncFetch.js` but getting the error:
 **The maximum number of studies per chart has been reached for current subscription**

run this file continuously
about 3-5 times continuously will appear the above error.

**To Reproduce**

here is my code : 

```js

const TradingView = require("@mathieuc/tradingview");

/**
 * This examples synchronously fetches data from 3 indicators
 */

const client = new TradingView.Client();
const chart = new client.Session.Chart();
chart.setMarket('BINANCE:DOTUSDT');

function getIndicData(indicator) {
  return new Promise((res) => {
    const STD = new chart.Study(indicator);

    console.log(`Getting "${indicator.description}"...`);

    STD.onUpdate(() => {
      res(STD.periods);
      console.log(`"${indicator.description}" done !`);
    });
  });
}

(async () => {
  console.log('Getting all indicators...');

  const indicData = await Promise.all([
    await TradingView.getIndicator('PUB;3lEKXjKWycY5fFZRYYujEy8fxzRRUyF3'),
    await TradingView.getIndicator('PUB;5nawr3gCESvSHQfOhrLPqQqT4zM23w3X'),
    await TradingView.getIndicator('PUB;vrOJcNRPULteowIsuP6iHn3GIxBJdXwT'),
  ].map(getIndicData));

  console.log(indicData);
  console.log('All done !');

  client.end();
})();

```

**Expected behavior**

can run normally

**Screenshots**

<img width="803" alt="1" src="https://github.com/user-attachments/assets/877b5fba-51d5-4dad-a970-1b2b01637cf1" />

Full Test : 

![full-gif](https://github.com/user-attachments/assets/96e416ff-7ce1-4b9c-ada2-3f8e7df536f7)

**Environment:**
 - OS: MacOs 
 - Node version: v23.3.0

**Additional context**

run this file continuously about 3-5 times continuously will appear the above error.

**Comment by hoangsoft90** [comment]
i got same error, may TV block api for this library

**Comment by huynhduc96** [comment]
@Mathieu2301  if TV block api or session , Is there any command or way to reset session?

**Comment by jazarja** [comment]
May be implement proxy support will solve the issue?

**Comment by hoangsoft90** [comment]
i run on vps but it not working. Before 1 month ago, it working on my laptop without 1.1.1.1 cloudflare, and today it not working. So conclusion is TV changed the rule?

**Comment by huynhduc96** [comment]
@jazarja 
> Seems this issue can be solved by login to your account.

is there no other way to get past it ? Really don't want to use my account :(

**Comment by hoangsoft90** [comment]
even login with free account, still not working.

**Comment by huynhduc96** [comment]
Can anyone help ? 😢
