### ISSUE TITLE
Do I need a premium plan to retrieve data?

### ISSUE THREAD

**Issue by xandervx** [Mathieu2301/TradingView-API#27]
I was wondering if I need an account with a paid plan to retrieve data using your API. I haven't found that they restrict any data to premium, only some UI functions.

**Comment by Mathieu2301** [comment]
No, you don't need a Premium TradingView account if you don't use premium features (Under-minute timeframes, special chart types (Renko, Kagi, etc...), Volume Profile, etc...)

**Comment by ADTC** [comment]
@Mathieu2301 is this still true? I couldn't find any info regarding the minimum TradingView plan required in your `README.md` file. Would be nice to have it updated there.
