### ISSUE TITLE
Doc about how to get the ID of an indicator

### ISSUE THREAD

**Issue by MrKitai** [Mathieu2301/TradingView-API#29]
I've been testing this today, and it's not as clear how to get and ID of an indicator that's not public, but published by another user and with closed source.

I see you're using WebSockets and the browser developer tools, but if you could explain it a bit more, it could help.

This is allowing me to automate some things i could not automate with other tools, so. Thanks!

**Comment by Mathieu2301** [comment]
You should use the `searchIndicator` function of V3.

**Comment by MrKitai** [comment]
Ahhh, so easy with that function in the v3.0 branch.

Thanks!
