### ISSUE TITLE
I have a little issue and i don't know how to solve it

### ISSUE THREAD

**Issue by z1kary** [Mathieu2301/TradingView-API#33]
./node_modules/@mathieuc/tradingview/miscRequests.js 306:43
Module parse failed: Unexpected token (306:43)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         name: input.name,
|         type: input.type,
>         value: settings[input.internalID] ?? settings[i] ?? input.defval,
|         defVal: input.defval,
|         hidden: !!input.isHidden,

thank in advance

**Comment by z1kary** [comment]
for the answer, just replace ?? by ||

**Comment by Mathieu2301** [comment]
You can replace '??' by '||' or use Node 14 or newer.
