### ISSUE TITLE
Cant find Incidator ID

### ISSUE THREAD

**Issue by Timmnn** [Mathieu2301/TradingView-API#42]
Where do I find the Indicator Id to put here:
![image](https://user-images.githubusercontent.com/13587412/147394285-7b4766cf-6e19-4b84-a6ef-85829bfaddba.png)

**Comment by revskill10** [comment]
@Timmnn What's your answer ?

**Comment by Mathieu2301** [comment]
You can use the `searchIndicator` function or check the DevTools.

**Comment by BlackPhoenixSlo** [comment]
I want to get invite only indicator id that I am invited to. How can I do that?

**Comment by 0xhex** [comment]
> I want to get invite only indicator id that I am invited to. How can I do that?

hello, any solution?

**Comment by BlackPhoenixSlo** [comment]
> > I want to get invite only indicator id that I am invited to. How can I do that?
> 
> hello, any solution?

https://www.youtube.com/watch?v=fWO-YYJAYgE
