### ISSUE TITLE
Internal server error on fetching private indicator - wrong color value of input

### ISSUE THREAD

**Issue by Sniffie** [Mathieu2301/TradingView-API#44]
Hi,

i'm getting an error on fetching a private indicator with the following message:
![image](https://user-images.githubusercontent.com/15264266/147423644-78ca00e4-c771-4b2c-85da-cdadb1065973.png)

Here are the default settings of the script, which are sent to the websocket (with an rgba value):
![image](https://user-images.githubusercontent.com/15264266/147423690-801331ca-7441-4884-9ef9-3126f7f5e1de.png)

Here is the websocket message of the tradingview gui:
![image](https://user-images.githubusercontent.com/15264266/147423707-4655bb27-3e79-403c-8a7d-b83a9e7a99e2.png)

I don't know the color value. It's not rgb, hex, etc... Any idea how to fix this?

**Comment by Mathieu2301** [comment]
I don't know how TW processes the colors but I know it depends on the script.
Did you tried this:
```javascript
indic.setOption('bg', 4285982208);
// or
indic.setOption(15, 4285982208);
```
?

**Comment by Sniffie** [comment]
Yes, that worked ;-) Thank you!
