### ISSUE TITLE
Error message "Max state sessions reached" 

### ISSUE THREAD

**Issue by Sniffie** [Mathieu2301/TradingView-API#45]
Hi,
after some testing i get the error message "Max state sessions reached" each time since 6 hours. I already closed all browser sessions, created a new session with a new token, but it doesnt help.
Any idea?

**Comment by Mathieu2301** [comment]
So this happens when you creates a logged client ?

**Comment by Sniffie** [comment]
Yes, but it's working again. I will update this issue, if I get the error message again... Thanks!
