### ISSUE TITLE
MarketAPI() is not a function

### ISSUE THREAD

**Issue by MartinBTCUSDT** [Mathieu2301/TradingView-API#49]
I have npm and node running on a centos 7 server.
When i try to run your script it keeps giving me the following error and i'm not sure why
`  const market = marketAPI();
                 ^
TypeError: marketAPI is not a function
`
And this is the part of the script where MarketAPI gets called:
  var mysql = require("mysql");
  const marketAPI = require("@mathieuc/tradingview");
  
  var con = mysql.createConnection({
    host: "127.0.0.1",
    user: "newuser",
    password: "password"
  });
  
  con.connect(function(err) {
    if (err) throw err;
    console.log("Connected!");
  });
  
  (async () => {
    const market = marketAPI();
  
    market.on("logged", async () => {
      console.log("API LOGGED");
  
      const searchBTC = (await market.search("bitcoin euro", "crypto"))[0];
      market.subscribe(searchBTC.id);

**Comment by Mathieu2301** [comment]
Hello, you are using the v2 syntax. Please look at [./examples](https://github.com/Mathieu2301/TradingView-API/tree/main/examples).
