### ISSUE TITLE
Can't get more than 5000 candles

### ISSUE THREAD

**Issue by SirMacke** [Mathieu2301/TradingView-API#50]
Hi,

I've been trying to get more than 5k one minute candles from tradingview. I noticed that with a free tradingview account you couldn't get more than 5k so I signed up for their free trial. Took out the "sessionid" cookie from the browser and inserted it to the script like below:

`const client = new TradingView.Client({ token: 'code goes here' });`

Tried to query one minute candles that are older than 7 days ago but it still wouldn't work.

I tried querying in the browser, i.e scroll back 7+ days on tradingview and that worked. So I don't think the issue comes from me having an account with a free trial on it.

Is there anything else that I'm doing wrong or is there anything with the library that needs to be fixed?

Here's some more of my code if that's interesting:

`
     // Script
    const chart = new client.Session.Chart();
    chart.setMarket(symbol, {
      timeframe: timeframe.toString(),
      range: range, // Can be positive to get before or negative to get after
      to: to - (60 * range * i),
    });
  
    let MA50 = { periods: [] };
    TradingView.getIndicator('STD;EMA').then(async (indic) => {
      indic.setOption(0, 50);
      indic.setOption(1, 'close');
      indic.setOption(2, 0);
      console.log(`Loading '${indic.description}' study...`);
      MA50 = new chart.Study(indic);
    });
  
    let MA200 = { periods: [] };
    TradingView.getIndicator('STD;EMA').then(async (indic) => {
      indic.setOption(0, 200);
      indic.setOption(1, 'close');
      indic.setOption(2, 0);
      console.log(`Loading '${indic.description}' study...`);
      MA200 = new chart.Study(indic);
    });
    
    await delay(5000);
    console.log(chart.periods.length)
    console.log(MA50.periods.length)
    console.log(MA200.periods.length)
`

Thanks for the help beforehand! :)

**Comment by Mathieu2301** [comment]
Hello, did you tried the `chart.fetchMore(n)` function ?

**Comment by Mathieu2301** [comment]
Maybe we can't fetch more than 5000 candles in one time but since TradingView's chart are using a `fetch_more` packet, we can try to do the same.

**Comment by SirMacke** [comment]
ah okay. Didn't know about that function, I'll have to try later. Thanks!

**Comment by Sniffie** [comment]
Hi! I tried it with a fetchMore call in onReady function with the same range (Max 5 recursion Calls with a range of 5000 elements). On 60 min candles i get 14000 results, on 15min only 6800.
Any idea whats going wrong?

**Comment by Sniffie** [comment]
Ok, it is limited by tradingview
https://www.tradingview.com/support/solutions/43000480679-i-can-t-see-all-historical-data-on-resolutions-lower-than-1-day/

**Comment by 0x090909** [comment]
I figured out this thing, you actually only need to set a different server name, and you'll be able to fetch more than 5k bars

**Comment by CryptoTr4der** [comment]
Yes but normally you can't get more than 25k candles, depends on the timeframe

**Comment by 0x090909** [comment]
@CryptoTr4der why would you even need more? Even if you need more you can do more separate sessions to increase that number

**Comment by CryptoTr4der** [comment]
e.g. to backtest a 1/3/5m Timeframe in combination with higher timeframes
