### ISSUE TITLE
Error message "study_not_auth:Script@tv..."

### ISSUE THREAD

**Issue by Sniffie** [Mathieu2301/TradingView-API#52]
Hi,
after some hours of fetching indicator values, i get the following error message in the onError event handler for each indicator:
"study_not_auth:Script@tv-scripting..."
Does anybody know how i can handle this error and start fetching again without restarting the node js process?

**Comment by Mathieu2301** [comment]
Interesting... Can you please send here an example of code? Is the indicator private (or invite-only) ?

After this error, I think you don't need to restart the process, just end the client and recreate one.

**Comment by Sniffie** [comment]
Sorry for the late reply... I can't create a example, because the error is fired after some hours of fetching periodically.
It's not just one single indicator, all indicators (~ 20) are throwing this error at the same time...

**Comment by Mathieu2301** [comment]
So it can happend with any indicator ?

**Comment by Sniffie** [comment]
Sorry for the late answer! 
Yes, im using now forever npm Script, which restarts the process of fetching data when this error occurs...
