### ISSUE TITLE
Compile the code

### ISSUE THREAD

**Issue by MagnusFriedl** [Mathieu2301/TradingView-API#57]
Hi there,
until now I have no experience with VS Code, Electronjs or Express. I've been trying to start "TV API" for 2 weeks, but so far no way has led to the goal. So I would appreciate if someone could tell me how i get the code to run.
Many Thanks.
Magnus

**Comment by Mathieu2301** [comment]
JavaScript is not a compiled language

**Comment by MagnusFriedl** [comment]
ok thanks, but how can i use this codes?

**Comment by Mathieu2301** [comment]
You can find all the examples and snippets in [`./examples`](https://github.com/Mathieu2301/TradingView-API/tree/main/examples) folder.
