### ISSUE TITLE
Internal server study error with color parameter

### ISSUE THREAD

**Issue by cslimani** [Mathieu2301/TradingView-API#58]
Hi,

I run test.js with a private indicator and I got this error : 
'Internal server study error: java.lang.NumberFormatException: For input string: "rgba(255,106,0,0.2)", Command info:

![image](https://user-images.githubusercontent.com/34135014/152007092-e268908c-a74f-468c-b828-08295d0ac2a7.png)

It seems it does not like that there is a color parameter but it is a problem with your code or from the server  ?

**Comment by Mathieu2301** [comment]
Since I don't have access to the indicator, I can't tell you where this error comes from.

**Comment by Mathieu2301** [comment]
But I've seen something like this before: #44

**Comment by Mathieu2301** [comment]
Fixed in [81c2e7e](https://github.com/Mathieu2301/TradingView-API/commit/81c2e7e7cbfd90b7bda1a2962289bd0069dbcf6a) !
