### ISSUE TITLE
[Indicators] How to set some parameters?

### ISSUE THREAD

**Issue by Ph3nol** [Mathieu2301/TradingView-API#61]
Hello there,

I'm looking for a solution to set some parameters to indicators.
It seems not to be possible to do with this version from `TradingView.getIndicator(...)`, but it was in a previous one (https://github.com/Mathieu2301/TradingView-API/blob/54b3bb3ed7390452baa4533c377a8f34d39cf917/tests/indicator.js#L16).

Any clue about it?

Thank you so much.

**Comment by Mathieu2301** [comment]
Hello !
You have to use the `setOption('option', 'value')` method like this :

```javascript
const volumeProfile = new TradingView.BuiltInIndicator('VbPFixed@tv-basicstudies-139!');
volumeProfile.setOption('first_bar_time', Date.now() - 10 ** 8);
```
or
```javascript
const indicator = TradingView.getIndicator('STD;Supertrend');
indicator.setOption('ATR_Length', 15);
```

The library is fully JSDoc-ed, which is why there are a lot of examples missing in the directory.

**Comment by Ph3nol** [comment]
Pretty cool! Awesome!
Thank you so much!

**Comment by Ph3nol** [comment]
Hey @Mathieu2301!

I've tries to use `indicator.setOption()` but indicator from `TradingView.getInficator('PUB;xxx')` seems to be a Promise... So, impossible to set options on it.

Any clue about it?

Thank you so much.

**Comment by Mathieu2301** [comment]
Sorry, just add `await` :

```javascript
const indicator = await TradingView.getIndicator('STD;Supertrend'); indicator.setOption('ATR_Length', 15);
```

**Comment by Ph3nol** [comment]
That's perfect! It works!

But with my indicator option, I have a strange server error from Study.
I think it's independant from your library...

![image](https://user-images.githubusercontent.com/183984/152806274-d39efd79-05a8-4407-87b2-368000b3a243.png)

I will investigate on it.

Thank you so much.

**Comment by Mathieu2301** [comment]
This error is known (#44, #58). I think it happens when you define a color type parameter with a string instead of a number.

**Comment by Ph3nol** [comment]
In fact, I don't set any parameters.

```
const indicator = await TradingView.getIndicator('PUB;xxx')
const study = new chart.Study(indicator)
```

I just use `await TradingView.getIndicator('PUB;xxx')` instead of using a Promise with `TradingView.getIndicator('PUB;xxx').then(...)`.

So I think it's not really a problem of parameters type.

**Comment by Mathieu2301** [comment]
Hmm interesting...
I could probably fix this but I don't have an example (public) indicator that throws this kind of error. I think I'll try to make one...

**Comment by Ph3nol** [comment]
@Mathieu2301, if it can help, it seems to depend on indicators themselves...

For example, it's OK for the classic Supertrend indicator (`PUB;VfOPXWDHDPhORvJYRTcuHOyeqpOcRR45`), but not for SSL Channel by MissTricky (`PUB;40f0a0bb7352417197de55d5ff06b33b`) or NSDT HAMA Candles by NorthStarDayTrading (`PUB;5d1dd1192c2348f6a7a511e90d909be7`).

Here are 2 simple example to fast-test and reproduce cases.

### OK case

```
const TradingView = require('@mathieuc/tradingview');

(async () => {
    const client = new TradingView.Client()
    const chart = new client.Session.Chart()
    chart.setMarket('BINANCE:BTCUSDT', { timeframe: '5', range: 5 })

    TradingView.getIndicator('PUB;VfOPXWDHDPhORvJYRTcuHOyeqpOcRR45')
        .then(pineIndicator => {
            const study = new chart.Study(pineIndicator)
            study.onUpdate(() => {
                console.log(study.periods)
            })
        })
})();
```

### NOK case

```
const TradingView = require('@mathieuc/tradingview');

(async () => {
    const client = new TradingView.Client()
    const chart = new client.Session.Chart()
    chart.setMarket('BINANCE:BTCUSDT', { timeframe: '5', range: 5 })

    TradingView.getIndicator('PUB;5d1dd1192c2348f6a7a511e90d909be7')
        .then(pineIndicator => {
            const study = new chart.Study(pineIndicator)
            study.onUpdate(() => {
                console.log(study.periods)
            })
        })
})();
```

I hope i will help! 😅

Thank you for your work, your patience and your help. 💪

**Comment by Mathieu2301** [comment]
Nice thank you ! So that :
```javascript
  ...
  pineIndicator.setOption('in_0', 0);
  pineIndicator.setOption('in_1', 0);
  pineIndicator.setOption('in_2', 0);
  pineIndicator.setOption('in_5', 0);

  const study = new chart.Study(pineIndicator);
  ...
```

could temporarily fix the problem... 🤔

**Comment by Ph3nol** [comment]
Thank you so much for this! 🙌🤩

When do you plan to release it?
