### ISSUE TITLE
Automatically reconnect after Internet connectivity changes

### ISSUE THREAD

**Issue by neelahagga** [Mathieu2301/TradingView-API#65]
Sorry to be disturbing you again.
The `onUpdate` method is not called after internet connectivity is lost, even after it comes back on again. I know it's pretty dumb to ask and I can listen to internet connectivity changes myself and restart the client, but I want to have least footprint on battery life. Automatically reconnecting after internet connectivity is regained and optionally providing some sort of listener for it would come in handy 🐒

**Comment by Mathieu2301** [comment]
I tried creating a client, disconnecting from the internet, and reconnecting the internet about 30 seconds later and the client automatically reconnects.

**Comment by Mathieu2301** [comment]
For longer disconnects, the socket connection should timeout by firing the `close` event:
```js
client.onDisconnected(() => {
  // reconnect here
});
```

**Comment by Mathieu2301** [comment]
The `onDisconnected` event fires when the internet connection comes back after a long time without. So it's the perfect time to reconnect.

If you want to know when you lost the connection, you can use the `ping` event:
```js
let lastPing = 0;
client.onPing(() => {
  lastPing = Date.now();
  setTimeout(() => {
    if (lastPing + 10000 > Date.now()) return;
    console.log('DISCONNECTED !');
    // TRY to reconnect here
  }, 11000);
});
```

**Comment by neelahagga** [comment]
The nodejs library I'm using shows strange behaviour everywhere.
Test code:
```
const TradingView = require('../main');
const sym1= 'CAPITALCOM:US100';
const sym2='CAPITALCOM:NATURALGAS';
const chartInterval='1';


const client = new TradingView.Client(); // Creates a websocket client

const chart1 = new client.Session.Chart(); // Init a Chart session
const chart2 = new client.Session.Chart();

chart1.setMarket(sym1, { // Set the market
  timeframe: chartInterval,
});
chart2.setMarket(sym2, { // Set the market
  timeframe: chartInterval,
});

chart1.onError((...err) => {console.error('Chart error:', ...err);});
chart2.onError((...err) => {console.error('Chart error:', ...err);});

chart1.onUpdate(() => { // When price changes
  if (!chart1.periods[0]) return;
  console.log(`[${chart1.infos.description}]: ${chart1.periods[0].close} ${chart1.infos.currency_id}`);
});
chart2.onUpdate(() => { // When price changes
  if (!chart2.periods[0]) return;
  console.log(`[${chart2.infos.description}]: ${chart2.periods[0].close} ${chart2.infos.currency_id}`);
});

let lastPing = 0;
client.onPing(() => {
  lastPing = Date.now();
  setTimeout(() => {
    if (lastPing + 10000 > Date.now()) return;
    console.log('DISCONNECTED !');
    // TRY to reconnect here
  }, 11000);
});

setInterval(() => {
  console.log(client.isOpen);
}, 2000);
```
The ping part never executes, i.e., the `'DISCONNECTED !'` is never printed even after waiting for long enough.
Anyways,  the client.isOpen() keeps returning false after internet is lost once, no matter whether it comes back.

I've no problem with the checking `isOpen()` every few seconds thing I'm currently using.
If there's a considerably more efficient way you already know of, please share it. Else probably close/delete the issue.

**Comment by Mathieu2301** [comment]
It's weird that the `ping` event doen't fire.
So what about the `close` event ?

**Comment by Mathieu2301** [comment]
For a better display of the debug mode, install and require the package `@mathieuc/console`.

**Comment by alikabeer32** [comment]
@neelahagga @Mathieu2301 How do you actually reconnect? What is the code to do that?

**Comment by Mathieu2301** [comment]
> @neelahagga @Mathieu2301 How do you actually reconnect? What is the code to do that?

It reconnects automatically when connection returns.

**Comment by alikabeer32** [comment]
> > @neelahagga @Mathieu2301 How do you actually reconnect? What is the code to do that?
> 
> It reconnects automatically when connection returns.

No it won't for me. It just stops updating even after the internet is back.

**Comment by muhrizkiakbar** [comment]
.

**Comment by muhrizkiakbar** [comment]
> For longer disconnects, the socket connection should timeout, firing the `close` event:
> 
> ```js
> client.onDisconnected(() => {
>   // reconnect here
> });
> ```

can you give example how to reconnect?
