### ISSUE TITLE
Backtesting a Pine Strategy

### ISSUE THREAD

**Issue by mtahreemalam** [Mathieu2301/TradingView-API#68]
Hello,
I have a customized strategy in pinescript. I need to test an like a million different parameters to determine the best combination.
I cant do that via TV. For it to be done via your API, will we need to first code it in Java?
And how much quicker it will be to test those parameters vs TV?
@Mathieu2301

**Comment by mtahreemalam** [comment]
Would it be possible to code a supertrend strategy in Pinescript?

**Comment by Mathieu2301** [comment]
I don't really understand the point of doing that since we can also get the performances of a pine strategy, but yes it is possible.

**Comment by mtahreemalam** [comment]
If we can get the performance of pine strategy its perfect. Thats why i asked the question before if we will a strategy in Javascript to optimize its parameters via your API, or will pinescript work.
Now that you have mentioned pinescript will work. Can you please tell me will all strategies as available on tradingview will be available via the API or is their a limitation?

**Comment by Mathieu2301** [comment]
> Can you please tell me will all strategies as available on tradingview will be available via the API or is their a limitation?

At the moment we have not found a Tradingview indicator that does not work with the library.

**Comment by mtahreemalam** [comment]
> > Can you please tell me will all strategies as available on tradingview will be available via the API or is their a limitation?
> 
> At the moment we have not found a Tradingview indicator that does not work with the library.

Thats great. Can you help me install and run it on my PC?

**Comment by mtahreemalam** [comment]
Ive installed and ran it. Can you please guide me with the commands, to backtest strategy results with multiple parameters

**Comment by Mathieu2301** [comment]
You have many examples in the [`./examples`](https://github.com/Mathieu2301/TradingView-API/tree/main/examples) repository.
I can't help everyone especially for questions that are not related to the library but JavaScript.
