### ISSUE TITLE
Where can I find instructions that shows how to use this code?

### ISSUE THREAD

**Issue by rimorae** [Mathieu2301/TradingView-API#69]
aint there any videos or instructions that shows how to use this code ,to run in, like what to do?

**Comment by Mathieu2301** [comment]
You have many examples in the [`./examples`](https://github.com/Mathieu2301/TradingView-API/tree/main/examples) folder.

**Comment by rimorae** [comment]
> You have many examples in the [`./examples`](https://github.com/Mathieu2301/TradingView-API/tree/main/examples) folder.

do i launch it through chrome ? cause it just says it cant launch, something about localhost

**Comment by Mathieu2301** [comment]
No, you must use NodeJS

**Comment by rimorae** [comment]
> No, you must use NodeJS

use it in visual studio code ?

**Comment by Mathieu2301** [comment]
Yes
