### ISSUE TITLE
Data id indicator not correct ? 

### ISSUE THREAD

**Issue by duclh-2011** [Mathieu2301/TradingView-API#70]
Hi @Mathieu2301  ! 
i try to get data from basic indicator name Volume 

![image](https://user-images.githubusercontent.com/54925990/155075823-12a53313-77b2-4fc5-a7c9-08845399f859.png)
 
When i check  data-id 
it's : **Volume@tv-basicstudies**

![image](https://user-images.githubusercontent.com/54925990/155076046-0570ea99-01df-426c-8f8b-87c09bbeda14.png)

yeah, normally i use this to get the indicator id , and it works.
But when I get this ID, I get the following error:

<img width="942" alt="Screen Shot 2022-02-22 at 15 37 43" src="https://user-images.githubusercontent.com/54925990/155076338-443ba018-155b-4f01-8a25-fa7a94f0f210.png">

i think it is a very basic indicator, so many people will get same problem with me. can you check it ?

P/s :  I tried using **searchIndicator** function to search for this indicator id, but to my surprise, it wasn't in the search results. So, it so strange

**Comment by Mathieu2301** [comment]
Duplicate #19

**Comment by Mathieu2301** [comment]
Built-in indicators don't have an id

**Comment by duclh-2011** [comment]
@Mathieu2301  so, how i can get data volume ? can you teach me ?

**Comment by duclh-2011** [comment]
actually, I've been using this code for the past few months. and it works properly.
however, since last night, this code has been unusable.
The cause is the Volume indicator.
I think the tradingview just changed something...

<img width="716" alt="Screen Shot 2022-02-22 at 21 00 07" src="https://user-images.githubusercontent.com/54925990/155128159-cb7ce030-6d62-4ecc-b395-a2e29c6cbda9.png">

**Comment by Mathieu2301** [comment]
https://github.com/Mathieu2301/TradingView-API/issues/19#issuecomment-991760644

**Comment by duclh-2011** [comment]
my problem is not able to get data with Volume indicator ID. 
in this case, the id I found is : **Volume@tv-basicstudies**


> @Mathieu2301 actually, I've been using this code for the past few months. and it works properly. however, since last night, this code has been unusable. The cause is the Volume indicator. I think the tradingview just changed something...
> 
> <img alt="Screen Shot 2022-02-22 at 21 03 05" width="732" src="https://user-images.githubusercontent.com/54925990/155128573-76417aaf-8ab4-4002-a18f-d0e98098b9f7.png">

**Comment by duclh-2011** [comment]
it's not volume profile ! 
it just normal Volume indicator !

**Comment by Mathieu2301** [comment]
```js
new TradingView.BuiltInIndicator('Volume@tv-basicstudies-144');
```

**Comment by duclh-2011** [comment]
> 



> ```js
> new TradingView.BuiltInIndicator('Volume@tv-basicstudies-144');
> ```

@Mathieu2301  
how i can get all old data by array list  ?

**Comment by Mathieu2301** [comment]
```js
const volume = new TradingView.BuiltInIndicator('Volume@tv-basicstudies-144');
const VOL = new chart.Study(volume);

VOL.onUpdate(() => {
  console.log(VOL.periods);
});
```

**Comment by duclh-2011** [comment]
@Mathieu2301  

i don't need update new data, i just nead all old data, and keep it in array to excute logic 
 
how i can do that. ?

**Comment by Mathieu2301** [comment]
Close the client after the first update and all the data is in `VOL.periods`.

**Comment by duclh-2011** [comment]
@Mathieu2301 

```javascript
const client = new TradingView.Client();
const chart = new client.Session.Chart();
chart.setMarket("BINANCE:BTCUSDT", {
  timeframe: "60",
  range: 1,
});

const volume = new TradingView.BuiltInIndicator("Volume@tv-basicstudies-144");
const VOL = new chart.Study(volume);

VOL.onUpdate(() => {
  console.log(VOL.periods);
  client.end();
});

console.log(VOL.periods);  // <--  just one item , I need the data of the previous candles.
```

i tried like this, but it only get 1 data of current candle.
I need the data of the previous candles.
can you help me ?

**Comment by Mathieu2301** [comment]
...

`range: 1`

**Comment by duclh-2011** [comment]
@Mathieu2301 
oh, i got it,
but is there any other way?

**Comment by Mathieu2301** [comment]
No, now please stop and read the examples.
