### ISSUE TITLE
Support google login

### ISSUE THREAD

**Issue by gbarton** [Mathieu2301/TradingView-API#78]
Is it possible to support login to TV via google auth?

**Comment by Mathieu2301** [comment]
Hello,
I think it doesn't make sense to implement it because it will necessarily require human action.
Using login with username/email and password every time is not really recommended. It is preferable to use a session token.

**Comment by gbarton** [comment]
Would it be possible to pass in the session token from the browser into node to use it?  I had to do something similar to that in the etrade api I was using and it worked.  It did mean manual first init, but then it would run and refresh the token fine.

**Comment by Mathieu2301** [comment]
Yes this is the first way to authenticate, it is the 'sessionid' cookie.

**Comment by gbarton** [comment]
That would be perfect! Can you point me to where that is? I didnt see an obvious way to set it, do you have a test or example of it?

**Comment by Mathieu2301** [comment]
Please read the readme.md

**Comment by Mathieu2301** [comment]
And check the examples

**Comment by Mathieu2301** [comment]
The session token is the 'sessionid' cookie.

**Comment by gbarton** [comment]
I have been, I think I found it, thank you.

For anyone else looking, its looks like its in the CustomTimeframe.js example here:

https://github.com/Mathieu2301/TradingView-API/blob/b0ebd8936a10efd3c62fa5c312561a85286012d1/examples/CustomTimeframe.js
