### ISSUE TITLE
I'm the tv premium member, but don't get more than 5000 candles for backtesting

### ISSUE THREAD

**Issue by klguang** [Mathieu2301/TradingView-API#90]
I'm very interested in this lib,  and i need to  automatically backtest. 
Thanks very much.

The result of the following test is 
> indicator periods[0]: { '$time': 1650009600, Plot: 5012 }

change the "range" field don't work in "setMarket" method

**Comment by klguang** [comment]
const TradingView = require('..//../main');

/*
  This example tests an indicator that sends
  graphic data such as 'lines', 'labels',
  'boxes', 'tables', 'polygons', etc...
*/

const client = new TradingView.Client({
  token: 'b6yueekz0zo24k9813e4iq27rfzxbup4',
});

const chart = new client.Session.Chart();
chart.setMarket('BINANCE:BTCUSDT', {
  timeframe: '240',
  //range: 10000,
});



TradingView.getIndicator('USER;d9088fcb65d24c22a9b37726a12a4800').then((indic) => {
// TradingView.getIndicator('PUB;5xi4DbWeuIQrU0Fx6ZKiI2odDvIW9q2j').then((indic) => {
//TradingView.getIndicator('STD;Zig_Zag').then((indic) => {
  const STD = new chart.Study(indic);

  STD.onError((...err) => {
    console.log('Study error:', ...err);
  });

  STD.onUpdate(() => {
    console.log(`STD '${STD.instance.description}' Loaded !`);

    console.log('Graphic data:', STD.graphic);
    console.log('Graphic periods:', STD.periods[0]);
    console.log('Graphic periods:', STD.periods[1]);
    console.log('Graphic periods:', STD.periods.length);
    console.log('Prices periods:', chart.periods.length);

    // console.log('Tables:', changes, STD.graphic.tables);
    // console.log('Cells', STD.graphic.tables[0].cells());
  
    chart.delete();
    client.end();
  });
  

});

**Comment by klguang** [comment]
pine script code
-----------
//@version=5
indicator("kline count")
var count = 0
count := count + 1
plot(count)

**Comment by Mathieu2301** [comment]
I fixed it last week !
Use the `prodata` server when you create the Client.
