### ISSUE TITLE
get buy and sell signal on indicators

### ISSUE THREAD

**Issue by kiaxseventh** [Mathieu2301/TradingView-API#91]
are you have solution for get buy and sell signal on indicators ?
for example on STD;Supertrend Indicator

I appreciate you a lot 

![Screenshot 2022-04-19 112530](https://user-images.githubusercontent.com/15640035/163944130-019a22f6-64af-467b-9302-d23117d52b71.png)

**Comment by PedramMarandi** [comment]
@kiaxseventh You can console.log what you receive from different indicators. I assume there is no general solution here and it all depends on that indicator's implementation.
