### ISSUE TITLE
replay stopped working

### ISSUE THREAD

**Issue by gbarton** [Mathieu2301/TradingView-API#93]
**Describe the bug**
Am getting a wierd error when I try to use replay.  Havent used it in a while and went to refresh my data and ran into the below error.
Its not sessionID, if i comment out my session Id I still get the error.

```
  trading:tv chart error, failing Critical error: +2s
Client critical error: [
  '{unknown_session_id,<<"replay_add_series">>,<<"rs_NdZz8nSz4tTl">>,\n' +
    '                    [<<"req_replay_addseries">>,\n' +
    '                     <<"={\\"symbol\\":\\"CURRENCYCOM:US30\\",\\"adjustment\\":\\"splits\\"}">>,\n' +
    '                     <<"60">>]}'
]
```

**To Reproduce**

Code I am using to replay, the onReplayLoaded function isnt called anymore:

```javascript
  const {
    duration,
    quoteStart,
    indicators,
    source,
    symbol,
  } = options;

  const market = `${source}:${symbol}`;
  // timeframe is in minutes (and a string)
  const timeframe = `${Math.floor(duration / 60)}`;

  const client = new TradingView.Client(clientConfig);
  const chart = new client.Session.Chart();
  const BATCH_SIZE = 100;
  const quoteStartDT = DateTime.fromSeconds(quoteStart);
  const marketConfig = {
    timeframe,
    // time to start from
    replay: quoteStart,
    range: BATCH_SIZE,
  };

  log(`pulling historical for ${market} (${timeframe}m) from: ${quoteStartDT.toISO()} batch: ${BATCH_SIZE}`);

  chart.setMarket(market, marketConfig);
  log('chart created for market', market, marketConfig);

  let replayEnd = false;

  chart.onError((err) => {
    log('chart error, failing', err);
  });

  // wait for the chart to be fully setup before executing
  chart.onReplayLoaded(async () => {
    log('replay mode ready');
    // more code
  });
```

**Expected behavior**
Pulled quotes

**Environment:**
 - OS: Ubuntu 19
 - Node version: 16.14.0

**Additional context**
Havent changed this code in a few months since it last worked.  Am wondering in TV changed their protocol or something?

**Comment by Mathieu2301** [comment]
Hello ! Are you using the npm version?

On the 5th of April, TV devs removed the replay support on the `widgetdata` server I fixed it by using the main `data` server in a commit 2 days later.
You have to use the latest version of TW-API to use replay mode :
```ruby
npm i github:Mathieu2301/TradingView-API
```

**Comment by gbarton** [comment]
Ahh ok thank you for responding!

I am using the npm version, are you planning to publish a new version to it soon or should I change to the github one for a while?
Maybe update the main page to say to use the github version for now?

**Comment by Mathieu2301** [comment]
> are you planning to publish a new version to it soon

I do not know yet

> should I change to the github one for a while?

Yes !

**Comment by gbarton** [comment]
ok ty, using the github version for now!
